apiVersion: 1

datasources:
  - name: Prometheus
    uid: PROMETHEUS
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: PostgreSQL
    uid: POSTGRESQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: crypto
    secureJsonData:
      password: crypto
    jsonData:
      database: crypto
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
